admin:
  address:
    socket_address: 
      address: 0.0.0.0
      port_value: 9901
dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
      set_node_on_first_message_only: true
static_resources:
  clusters:
  - connect_timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
    http2_protocol_options: {}
    name: xds_cluster
  - name: some_service
    connect_timeout: 10s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3000
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5000
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 7000
node:
  cluster: liqiang-dev-vm
  id: liuliqiang.dev.vm
